
  // THIS FILE IS AUTO-GENERATED
  // DO NOT EDIT THIS FILE DIRECTLY
  
  import Ajv from "ajv";
  import addFormats from "ajv-formats";
  import {BinanceWebSocketKlineMessage} from "../BinanceWebSocketKlineMessage";
  
  const ajv = new Ajv();
  addFormats(ajv, ["date-time"]);
  const validate = ajv.compile(
    {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/BinanceWebSocketKlineMessage",
  "definitions": {
    "BinanceWebSocketKlineMessage": {
      "type": "object",
      "properties": {
        "stream": {
          "type": "string"
        },
        "data": {
          "$ref": "#/definitions/BinanceWebSocketKlineEvent"
        }
      },
      "required": [
        "stream",
        "data"
      ]
    },
    "BinanceWebSocketKlineEvent": {
      "type": "object",
      "properties": {
        "e": {
          "type": "string",
          "const": "kline"
        },
        "E": {
          "type": "number"
        },
        "s": {
          "type": "string"
        },
        "k": {
          "type": "object",
          "properties": {
            "t": {
              "type": "number"
            },
            "T": {
              "type": "number"
            },
            "s": {
              "type": "string"
            },
            "i": {
              "type": "string"
            },
            "f": {
              "type": "number"
            },
            "L": {
              "type": "number"
            },
            "o": {
              "type": "string"
            },
            "c": {
              "type": "string"
            },
            "h": {
              "type": "string"
            },
            "l": {
              "type": "string"
            },
            "v": {
              "type": "string"
            },
            "n": {
              "type": "number"
            },
            "x": {
              "type": "boolean"
            },
            "q": {
              "type": "string"
            },
            "V": {
              "type": "string"
            },
            "Q": {
              "type": "string"
            },
            "B": {
              "type": "string"
            }
          },
          "required": [
            "t",
            "T",
            "s",
            "i",
            "f",
            "L",
            "o",
            "c",
            "h",
            "l",
            "v",
            "n",
            "x",
            "q",
            "V",
            "Q",
            "B"
          ]
        }
      },
      "required": [
        "e",
        "E",
        "s",
        "k"
      ]
    }
  }
}
  );
  
  export function isBinanceWebSocketKlineMessage(value: unknown): value is BinanceWebSocketKlineMessage {
    const isValid = validate(value);

    if (process.env.NODE_ENV === "development" && !isValid) {
      console.log(validate.errors?.map((e) => e.instancePath + ' ' + e.message).join(', ') || '');
    }

    return isValid;
  }
  