
  // THIS FILE IS AUTO-GENERATED
  // DO NOT EDIT THIS FILE DIRECTLY
  
  import Ajv from "ajv";
  import addFormats from "ajv-formats";
  import {BuyTradeInfo} from "../BuyTradeInfo";
  
  const ajv = new Ajv();
  addFormats(ajv, ["date-time"]);
  const validate = ajv.compile(
    {
  "$schema": "http://json-schema.org/draft-07/schema#",
  "$ref": "#/definitions/BuyTradeInfo",
  "definitions": {
    "BuyTradeInfo": {
      "type": "object",
      "properties": {
        "amount": {
          "type": "number"
        },
        "quoteAmount": {
          "type": "number"
        },
        "price": {
          "type": "number"
        },
        "timestamp": {
          "type": "number"
        },
        "low": {
          "type": "number"
        }
      },
      "required": [
        "amount",
        "quoteAmount",
        "price",
        "timestamp",
        "low"
      ]
    }
  }
}
  );
  
  export function isBuyTradeInfo(value: unknown): value is BuyTradeInfo {
    const isValid = validate(value);

    if (process.env.NODE_ENV === "development" && !isValid) {
      console.log(validate.errors?.map((e) => e.instancePath + ' ' + e.message).join(', ') || '');
    }

    return isValid;
  }
  