// THIS FILE IS AUTO-GENERATED
// DO NOT EDIT THIS FILE DIRECTLY

import Ajv from 'ajv';
import addFormats from 'ajv-formats';
import { IKline } from '../IKline';

const ajv = new Ajv();
addFormats(ajv, ['date-time']);
const validate = ajv.compile({
  $schema: 'http://json-schema.org/draft-07/schema#',
  $ref: '#/definitions/IKline',
  definitions: {
    IKline: {
      type: 'object',
      properties: {
        interval: {
          type: 'string',
        },
        start: {
          type: 'number',
        },
        end: {
          type: 'number',
        },
        open: {
          type: 'number',
        },
        close: {
          type: 'number',
        },
        high: {
          type: 'number',
        },
        low: {
          type: 'number',
        },
        volume: {
          type: 'number',
        },
      },
      required: [
        'interval',
        'start',
        'end',
        'open',
        'close',
        'high',
        'low',
        'volume',
      ],
    },
  },
});

export function isIKline(value: unknown): value is IKline {
  const isValid = validate(value);

  if (process.env.NODE_ENV === 'development' && !isValid) {
    console.log(
      validate.errors
        ?.map((e) => e.instancePath + ' ' + e.message)
        .join(', ') || ''
    );
  }

  return isValid;
}
